import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import backgroundDesktop from "/public/bg-intro-desktop.png";
import backgroundMobile from "/public/bg-intro-mobile.png";

const inter = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Intro component with signup form",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}{" "}
        <Image
          src={backgroundDesktop}
          alt="Background"
          className="absolute self-center -z-10 top-0 left-0 w-full h-full object-cover max-[375px]:hidden"
        />
        <Image
          src={backgroundMobile}
          alt="Background"
          className="absolute self-center -z-10 top-0 left-0 w-full h-full object-cover hidden max-[375px]:block"
        />
      </body>
    </html>
  );
}
